version: '2.4'

services:
  Nexus:
     image: Nexus
     build: ./Nexus
     command: python upstream_listener.py
     volumes:
        - "logs:/Nexus/logs"
     environment:
       receiver_queue: upstream
       downstream_sender: downstream1
       downstream_listener: downstream2
       gcd_sender: gcd1
       gcd_listener: gcd2
       src_system: Nexus
       mq_host: mq
       tracer_ip: tracer
       sleep_time: 60

  External:
     image: External
     build: ./External
     command: python listener.py
     volumes:
        - "logs:/External/logs "
     environment:
       receiver_queue: downstream1
       sender_queue: downstream2
       src_system: DOWN
       mq_host: mq
       tracer_ip: tracer
       sleep_time: 60

  GCD:
     image: GCD
     build: ./GCD
     command: python listener.py
     volumes:
        - "logs:/GCD/logs"
     environment:
       receiver_queue: gcd_sender
       sender_queue: gcd_listener
       src_system: GCD
       mq_host: mq
       tracer_ip: tracer
       sleep_time: 60

  Tracer:
     image: Tracer
     build: ./Tracer
     command: python run.py
     ports:
       - "5000":"5000"
     expose:
        - "5000"
     environment:
       mongo_addr: db
       mq_host : mq
       sender_queue: upstream


  LA:
     image: LA
     build: ./LogAggregator
     command: python log_aggregator.py
     volumes:
        - "logs:/LA/logs"
     environment:
       mongo_addr: db

volumes:
  logs: